# Generated by Django 4.0.2 on 2022-02-21 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Noutbuk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=60, unique=True, verbose_name='name Noutbook:')),
                ('brand', models.CharField(max_length=70, verbose_name='brand:')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('nout_type1', models.IntegerField(choices=[(1, 'Laptoop'), (2, 'Noutbook'), (3, 'MackBoock')], verbose_name='Nout-Type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
