# Generated by Django 4.0.2 on 2022-02-21 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noutbuk',
            name='descriptions',
            field=models.TextField(default=123, verbose_name='Описание:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='noutbuk',
            name='brand',
            field=models.CharField(max_length=70, verbose_name='Бренд:'),
        ),
        migrations.AlterField(
            model_name='noutbuk',
            name='name',
            field=models.CharField(db_index=True, max_length=60, unique=True, verbose_name=''),
        ),
    ]
