# Generated by Django 4.0.2 on 2022-02-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nout', '0002_noutbuk_descriptions_alter_noutbuk_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noutbuk',
            name='name',
            field=models.CharField(max_length=60, verbose_name=''),
        ),
    ]
